name: lvd

channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - menpo

dependencies:
  - python=3.8
  - pytorch==2.0.1
  - torchvision==0.15.2
  - torchaudio==2.0.2
  - pytorch-cuda=11.8
  - numpy
  - scikit-learn
  - scipy
  - matplotlib
  - trimesh
  - opencv
  - pyhull
  - cvxopt
  - pyopengl
  - mesa
  - menpo::osmesa
  - pyrender
  - pyquaternion
  - point_cloud_utils
  - tqdm
  - tensorboardx
  - ipython
  - pip
  - pip:
      - -r pip_requirements.txt
      - -r more_requirements.txt