name: lvd

channels:
  - pytorch
  - nvidia
  - defaults
  - conda-forge
  - menpo

dependencies:
  - python=3.8
  - pytorch=2.0.1=*cuda11.8*
  - torchvision=0.15.2=*cu118*
  - pytorch-cuda=11.8
  - numpy<1.24
  - scikit-learn
  - scipy
  - cvxopt
  - freeglut
  - ipython
  - imgaug
  - matplotlib
  - menpo::osmesa
  - mesa
  - opencv
  - pip
  - point_cloud_utils
  - pyhull
  - pyopengl
  - pyquaternion
  - pyrender
  - tensorboardx
  - tqdm
  - trimesh
  - pip:
      - -r requirements.txt
      - mediapipe
      - opendr
      - rembg[gpu,cli]
      - scikit-image
      - smplx
      - torchgeometry
      - git+https://github.com/hassony2/chumpy.git
      - ./manopth